Added equals and hashcode methods in Password API.
eclipse-kura/kura pull request #2534
Opened 2019-08-26 15:37 UTC by MMaiero

Signed-off-by: Maiero <matteo.maiero@eurotech.com>

2024-08-29 06:53 UTC, mattdibi commented
Since we're now working on a *major* release and we can perform breaking changes can we merge this? @MMaiero

2024-08-30 14:30 UTC, MMaiero commented
Not building. It needs to be rechecked

2026-02-17 16:21 UTC, salvatore-coppola commented
@mattdibi it's time to merge this, I don't want to assist to the 6th birthday

2026-02-18 11:01 UTC, mattdibi commented
@salvatore-coppola build is failing, cannot be merged as-is

2026-09-04 09:54 UTC, salvatore-coppola commented
@mattdibi THE TIME HAS COME !

2026-09-04 10:26 UTC, salvatore-coppola commented
Cleaned a little bit and updated the description

2026-09-04 11:47 UTC, marcellorinaldo requested changes

2026-09-04 11:47 UTC, marcellorinaldo commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/configuration/Password.java
> +    public boolean equals(Object obj) {
```java
  char[] x1 = new char[] {'a','b','c'};
  char[] x2 = new char[] {'a','b','c'};
  Password p1 = new Password(x1);
  Password p2 = new Password(x2);
  
  System.out.println(p1.equals(p2)); // true
  x1[1] = 'x';
  System.out.println(p1.equals(p2)); // false
```

Some other changes are needed. The two equals should return both true.

2026-09-04 11:52 UTC, marcellorinaldo requested changes
Moreover, some problems on `null` values (also prior this PR):

```java
Password p1 = new Password(null);
// produces error: reference to Password is ambiguous
```

```java
Password p1 = new Password((String) null);
p1.toString(); // throws NPE
```

2026-09-04 11:53 UTC, salvatore-coppola commented on kura/org.eclipse.kura.api/src/main/java/org/eclipse/kura/configuration/Password.java
> +    public boolean equals(Object obj) {
solved

2026-09-04 12:01 UTC, salvatore-coppola commented
> Moreover, some problems on `null` values (also prior this PR):
> 
> ```java
> Password p1 = new Password(null);
> // produces error: reference to Password is ambiguous
> ```
> 
> ```java
> Password p1 = new Password((String) null);
> p1.toString(); // throws NPE
> ```

Decide to maintain the tolerance for the null value for the password argument for backward compatibility.

2026-09-04 12:04 UTC, marcellorinaldo approved these changes

2026-09-04 12:10 UTC, marcellorinaldo commented
> > Moreover, some problems on `null` values (also prior this PR):
> > ```java
> > Password p1 = new Password(null);
> > // produces error: reference to Password is ambiguous
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```java
> > Password p1 = new Password((String) null);
> > p1.toString(); // throws NPE
> > ```
> 
> Decide to maintain the tolerance for the null value for the password argument for backward compatibility.

This commit is suspicious https://github.com/eclipse-kura/kura/commit/3ed5a1ef7c15ab1324da3186783c5b64be614ab2

2026-09-04 12:21 UTC, salvatore-coppola commented
We will merge in order to solve an old bug in a dependent component. Later, we will evaluate whether to remove the ability to allow null arguments.

2026-09-04 12:49 UTC, merged